#!/usr/bin/python3
def twoSum(nums, target):
   output = []
   for idi, i in enumerate(nums):
       for idj, j in enumerate(nums):
            if i + j == target and idi != idj:
                output.append(idi)
                output.append(idj)
                return tuple(output)
print(twoSum([2,7,11,15],9))
print(twoSum([3,2,4],6))
print(twoSum([3,3],6))
